defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 5dd08fc8-3ea4-4582-952f-4c0f7ebf409e # Category
handle: blogCategories
maxAuthors: 1
name: 'Blog Categories'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  58ccb571-6c72-449f-8e7b-6f43c5d416b3: # Twig
    enabledByDefault: true
    hasUrls: true
    template: _pages.twig
    uriFormat: 'categories/{slug}'
  c436ad5b-1a67-4fee-a936-b0c7032ba3c0: # Blade
    enabledByDefault: true
    hasUrls: true
    template: 'blade:entries.category'
    uriFormat: 'categories/{slug}'
structure:
  maxLevels: null
  uid: 3fa989b7-cc6c-402a-b995-5698a2b688ea
type: structure
