defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 697da4c2-e02f-4f49-9d76-e22609ceda25 # Page
handle: blogPosts
maxAuthors: 1
name: 'Blog Posts'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  58ccb571-6c72-449f-8e7b-6f43c5d416b3: # Twig
    enabledByDefault: true
    hasUrls: true
    template: _pages.twig
    uriFormat: 'blog/{slug}'
  c436ad5b-1a67-4fee-a936-b0c7032ba3c0: # Blade
    enabledByDefault: true
    hasUrls: true
    template: 'action:main/blog/post'
    uriFormat: 'blog/{slug}'
type: channel
