defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 25b2446d-c1d2-4aa1-8184-3147e617f069 # Text
handle: guestbookPosts
maxAuthors: 1
name: 'Guestbook Posts'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  58ccb571-6c72-449f-8e7b-6f43c5d416b3: # Twig
    enabledByDefault: true
    hasUrls: true
    template: _pages.twig
    uriFormat: 'posts/{slug}'
  c436ad5b-1a67-4fee-a936-b0c7032ba3c0: # Blade
    enabledByDefault: true
    hasUrls: true
    template: 'blade:entries.guestbook-post'
    uriFormat: 'posts/{slug}'
type: channel
